name: Deploy Medusa Store to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set ECR image URI
        id: vars
        run: |
          echo "REPO_URI=$(aws ecr describe-repositories --repository-names medusa-store --region us-east-1 --query 'repositories[0].repositoryUri' --output text)" >> $GITHUB_ENV

      - name: Build, tag, and push Docker image to ECR
        run: |
          docker build -t $REPO_URI:latest .
          docker push $REPO_URI:latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init & Apply
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve -var="container_image=${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}"
